### ISSUE TITLE
Allgemein: Spindel/Fräsmotor

### ISSUE THREAD

**Issue by ergerd** [mrRobot62/GCodeGenerator_Geometricals#10]
Sollte man die Möglichkeit  einbauen, den Fräsmotor am Anfang des Fräsjobs zu starten (M3) und am Ende zu stoppen (M5)?

**Comment by mrRobot62** [comment]
jo, guter Plan ! - Das könnte aber die Preamble und die PostAmble realisiert werden.

**Comment by mrRobot62** [comment]
Vorgesehen schon in V0.12.3 - Eingabefelder zwar vorhanden aber noch nicht ausprogrammiert

**Comment by mrRobot62** [comment]
Bugfix in 0.12.4 : Es gibt jetzt drei Eingabefelder ToolID, Spindle Speed, Spindle Richtung (CW/CCW). Im GCode wird das direkt in der Preamble eingefügt
