### ISSUE TITLE
Bedienung des GCodeGenerators - Kein Refresh des Dialoges bei erneuter Auswahl aus Menü

### ISSUE THREAD

**Issue by ergerd** [mrRobot62/GCodeGenerator_Geometricals#11]
Wird im Menü "File" eine anderer Menüpunkt ausgewählt, so erscheint die neue Auswahl unter der Alten. Ist das so gewollt?
![grafik](https://user-images.githubusercontent.com/44188762/48733304-8cdb9e80-ec42-11e8-80b3-862f2e3b641d.png)

**Comment by ergerd** [comment]
Betriebssystem: Windows 10

**Comment by mrRobot62** [comment]
Ja, leider ein bekannter Fehler - ich krieg das nicht hin :-O - Keine Ahnung wie das geht. Man muss derzeit neu starten

**Comment by mrRobot62** [comment]
bugfix V0.12.3 fälschlicherweise unter #15 diesen Fehler bereinigt
