### ISSUE TITLE
surface_milling_a_rectangle: Y-Achse

### ISSUE THREAD

**Issue by ergerd** [mrRobot62/GCodeGenerator_Geometricals#12]
Die Y-Achse wird nur vorgefahren, wenn X nach links fährt. Fährt X nach rechts fährt Y nicht vor.

**Comment by ergerd** [comment]
Ist eine Tiefe abgearbeitet, so fährt das Werkzeug in die nächste Tiefe, und steuert dann erst den neuen Startpunkt an. M.E. Werkzeug auf Safety Z, den neuen Startpunkt anfahren und dann auf die neue Tiefe gehen.

**Comment by mrRobot62** [comment]
Bugfix: Fehler #12a , Y-Achse korrigieren behoben
Bugfix: Fehler #12b, Zurück zum X0,Y0 wenn eine Tiefe fertig ist

**Comment by mrRobot62** [comment]
Bugfix Release V0.12.1

**Comment by ergerd** [comment]
Ich verstehe Stepover tooldia% nicht. Ich habe angenommen, je kleiner der Prozentwert ist, um so enger liegen die Bahnen zusammen. Das Gegenteil ist der Fall.

**Comment by mrRobot62** [comment]
StepOver: => Wert der Überlappung, 0% keine Überlappung, 50% = 50% Überlappung 90% = 90% Überlappung

Overshot: ==100%  der Fräser komplett fährt aus der Kontur raus. Im Prinzip ist dann die Kante des Werkstücks und die Kante des Fräsers auf einer Linie

größer als 100% der Fräser ist außerhalb der Kontor und zwar um soviel % wie der Radius des Tools. Also bei einen 12mm Fräser und einem Overshot von 110% müsste demnach der Fräser 10% von 6mm = 0,6mm außerhalb der Kontur liegen
