### ISSUE TITLE
mill_round_rectangle_pocket: Fertig?

### ISSUE THREAD

**Issue by ergerd** [mrRobot62/GCodeGenerator_Geometricals#13]
Ist das schon fertig? Das Ergebnis sieht komisch aus, ich habe als Größe 10 x 10 mm angegeben. Auch wird bei Angabe von depth cutting per step -0.5 sofort auf 1 mm Tiefe gefahren.
![grafik](https://user-images.githubusercontent.com/44188762/48803875-78b3a200-ed13-11e8-8997-4743251d978d.png)

**Comment by mrRobot62** [comment]
??? - das ist irgendwie Schrott :-O - keine Ahnung was da los ist - schaue ich mir morgen an

**Comment by mrRobot62** [comment]
das ist seltsam - bei mir klappt das. Bitte gib mir mal exakt die Einstellungen die du vorgenommen hast :-O

<img width="674" alt="bildschirmfoto 2018-11-21 um 18 20 31" src="https://user-images.githubusercontent.com/949032/48857875-3d1fe300-edba-11e8-853d-b142c6b969e6.png">

**Comment by mrRobot62** [comment]
Fehlerszenario konnte ich nachbauen

<img width="674" alt="bildschirmfoto 2018-11-21 um 19 07 45" src="https://user-images.githubusercontent.com/949032/48860347-f681b700-edc0-11e8-98a3-0281e27ad6b0.png">

**Ursache**:
Der Eckenradius steht per default auf 10mm. Wenn nun die Größe des Rechtecks ebenfalls auf 10x10 gesetzt wird, passt das ganze nicht - ist ja quasi ein Kreis. Dann kommt es zu solch einer Konstellation.

Dies wird durch die UserInputValidierung zur Zeit nicht abgefangen

**Comment by mrRobot62** [comment]
Fehler in V0.12.2 gefixt. Uservalidation prüft nun ob EdgeRadius <= ist als die doppelte Seitenlänge
