### ISSUE TITLE
mill_round_rectangle_pocket: Anfangstiefe nicht berücksichtigt

### ISSUE THREAD

**Issue by ergerd** [mrRobot62/GCodeGenerator_Geometricals#15]
Auch hier wird zwar depth cutting per step -0.5 angegeben, das Werkzeug taucht aber sofort auf 1 mm Tiefe ein.

**Comment by mrRobot62** [comment]
poste mal den GCode und welche Parametereinstellung du genommen hast

**Comment by mrRobot62** [comment]
bugfix V0.12.3

**Comment by ergerd** [comment]
Steht bugfix V0.12.3 schon zur Verfügung? Nach wie vor wird sofort auf 1mm Tiefe angefangen. Einstellungen Standard.

**Comment by ergerd** [comment]
Auch hier macht Stepover tooldia % kleiner 70 m.E. keinen Sinn.

**Comment by mrRobot62** [comment]
nein 12.3 ist noch nicht eingecheckt - die aktuelle Versionsnummer findest du IMMER im GitHub im Changelog - das aktualisiere ich immer nach einem Commit

Ok, dann ist das ein genereller Fehler mit dem ToolDia/Stepover.
