### ISSUE TITLE
mill_pocket_circle: Angabe von Raduis inner scheint keine Wirkung zu haben

### ISSUE THREAD

**Issue by ergerd** [mrRobot62/GCodeGenerator_Geometricals#16]
Als Radius outer circle habe ich 30.0 angegeben, als Radius inner in drei Versuchen 0.0, 10.0 und 20.0.
Es wurde nur immer ein Außenkreis gefräst.

**Comment by mrRobot62** [comment]
Fehler wurde gefixt. Ab V012.2 nicht mehr vorhanden

**Comment by ergerd** [comment]
1. Wozu braucht man Stepover tooldia % Werte kleiner als 70%? Wenn man unter 70% wählt, z.B. es auf der Grundeinstellung von 50% lässt, so bleiben Stege zwischen den einzelnen Kreisfahrten stehen. Ich kann mir nicht vorstellen das meine eine Kreistasche mit Stegen gebrauchen kann.
2. Ich habe für Stepover tooldia % 70 gewählt und alles andere so gelassen, dann bleibt ein Rest in der Mitte stehen.

**Comment by mrRobot62** [comment]
1) Die Idee ist ja, dass man einen Wert zwischen 30 und 90% einstellen kann. Sprich bei 30, sollte eine sehr große Überdeckung stattfinden und immer wieder nur 30% letztendlich der Vorschub ist. Das aber ein Steg entsteht ist wirklich nicht das es sein sollte :-O 

2) das kann nur damit zusammenhängen, dass es einen Rechenfehler bei der Berechnung des Restwertes auftritt :-O 

Tritt das bei allen Pockets auf?

**Comment by ergerd** [comment]
Zu 2: Nein, ist mir nur bei diesem aufgefallen.
--

**Comment by mrRobot62** [comment]
Das hier ist die Formel um Stepover zu berechnen - eigentlich ganz trivial

`stepover = round(toolDia - (float(toolDia * stepover) / 100), 1)`

bei Stepover 70% und ToolDia 6mm ergibt das:
```
stepover = round(6-(6*70)/100),1)
stepover = 6 - 4,2 
stepover = 1,8
```
Folglich wird von **G01 X0** die nächste Postion  **G01 X1,8** sein

**Comment by mrRobot62** [comment]
Hier mal ein Default-Beispiel GCode (70% Stepover)
Das wäre doch korrekt oder - oder ich versteh das ganze Problem einfach nicht :-O
```
(move Z-axis to start postion near surface)
G00 Z0003.000 F200.0 

(-- START DEPTH Loop --)
  (-- START Track Loop  --)

  (-- next depth z -000.500 --)
   G00 **X0027.000** Y0000.000 F0200.000
   G01 Z-000.500 F0050.000
   G02 I-027.000 F0080.000

  (-- next depth z -000.500 --)
   G00 **X0025.200** Y0000.000 F0200.000
   G01 Z-000.500 F0050.000
   G02 I-025.200 F0080.000

  (-- next depth z -000.500 --)
   G00 **X0023.400** Y0000.000 F0200.000
   G01 Z-000.500 F0050.000
   G02 I-023.400 F0080.000

  (-- next depth z -000.500 --)
   G00 **X0021.600** Y0000.000 F0200.000
   G01 Z-000.500 F0050.000
   G02 I-021.600 F0080.000

```

**Comment by mrRobot62** [comment]
So hier mal ein Test in CAMotics.

Bist du dir sicher, das du in Camotics auch ein korrektes 6mm Werkzeug definiert hast und dann im GCode auch Tx M6 manuell reingeschrieben hast?

Bei mir sieht das jetzt mit einem 6mm Tool so aus:

<img width="844" alt="bildschirmfoto 2018-11-26 um 20 07 00" src="https://user-images.githubusercontent.com/949032/49036081-0a5d5c80-f1b7-11e8-9f1a-35f5d76020e7.png">


hier das gleiche mit Stepover 70%
auch das sieht gut aus

<img width="842" alt="bildschirmfoto 2018-11-26 um 20 10 10" src="https://user-images.githubusercontent.com/949032/49036209-5e684100-f1b7-11e8-918d-beff939b6ec3.png">

**Comment by ergerd** [comment]
Nimm den Standardwert, dann sollte es sofort zu sehen sein.

**Comment by ergerd** [comment]
Ich schreibe nichts manuell irgendwo rein

**Comment by mrRobot62** [comment]
So hier ein Bild mit absoluten DEFAULT Werten
Bitte beachten: Wenn du den GCode einfach "so" in CAMotics lädtst dann wird als Default T1 genommen, dass ist bei mir ein 2,5 Fräser. Dann stimmt das natürlich nicht mit dem GCode überein. Dort gehen wir von einem 6mm Fräser aus - Folge => Stege

Also ich hab es so gemacht: in CAMotics habe ich mir einen Fräser angelegt der 6mm Durchmesser hat. (T4), sobald ich ein GCode file lade korrigiere ich den GCode und Schreibe dort T4 M6 zusätzlich nach dem Preamble rein.

Dann sieht das so aus:

<img width="755" alt="bildschirmfoto 2018-11-26 um 21 43 18" src="https://user-images.githubusercontent.com/949032/49041116-b3f71a80-f1c4-11e8-8332-8be17cf8c3a6.png">

**Comment by ergerd** [comment]
Ah, okay. Dann saß das Problem ja wieder 60 cm vorm Bildschirm :-)
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 26.11.18, 21:46, Bernd Klein <notifications@github.com> schrieb:
So hier ein Bild mit absoluten DEFAULT Werten
Bitte beachten: Wenn du den GCode einfach "so" in CAMotics lädtst dann wird als Default T1 genommen, dass ist bei mir ein 2,5 Fräser. Dann stimmt das natürlich nicht mit dem GCode überein. Dort gehen wir von einem 6mm Fräser aus - Folge => Stege
Also ich hab es so gemacht: in CAMotics habe ich mir einen Fräser angelegt der 6mm Durchmesser hat. (T4), sobald ich ein GCode file lade korrigiere ich den GCode und Schreibe dort T4 M6 zusätzlich nach dem Preamble rein.
Dann sieht das so aus:

**Comment by mrRobot62** [comment]
ich schließe dieses issue - kein Bugfix notwendig
