### ISSUE TITLE
GCodeGenerator - Quit funktioniert nur noch über Menü, Versionsnummer anzeigen

### ISSUE THREAD

**Issue by ergerd** [mrRobot62/GCodeGenerator_Geometricals#18]
In meiner Version wird das DOS-Fenster nicht mehr geschlossen, wenn ich den Generator über das Kreuz beende. Bei File -> Quit klappt es.

**Comment by ergerd** [comment]
Schön wäre es sich die Versionsnummer anzeigen zu lassen

**Comment by mrRobot62** [comment]
ja, das ein Überbleibsel aus meinem Versuch das Fenster zu schließen und dann mit einer neuen Auswahl neu zu öffnen. Hab ich vergessen zu erwähnen :-O

Versionsnummer ist eine sehr gute Idee

**Comment by mrRobot62** [comment]
Thema: Versionsnummer

<img width="277" alt="versionsnr" src="https://user-images.githubusercontent.com/949032/48984260-e556e400-f0f9-11e8-89e2-c46361d088fe.png">

**Comment by ergerd** [comment]
Cool!
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 25.11.18, 21:34, Bernd Klein <notifications@github.com> schrieb:
Thema: Versionsnummer

**Comment by mrRobot62** [comment]
Fenster schließen und über einen neuen Menüpunkt wieder öffnen kann in der 0.12.3 getestet werden
