### ISSUE TITLE
Millingparameters (millingparameters.json)

### ISSUE THREAD

**Issue by ergerd** [mrRobot62/GCodeGenerator_Geometricals#20]
1. Ähnliche Einträge werden nicht korrekt erkannt, es erscheinen 2 Häkchen in der Parameterliste (siehe Bild im Anhang).
![20190303_081505](https://user-images.githubusercontent.com/44188762/53692855-231d7580-3d97-11e9-8572-fa30de1297d1.jpg)
2. Ein scrollen bei einer größeren Anzahl von Einträgen ist nicht möglich.

**Comment by mrRobot62** [comment]
closed - fixed in release 0.12.5-rc2

**Comment by ergerd** [comment]
Perfect!
