### ISSUE TITLE
surface_milling_a_spiral

### ISSUE THREAD

**Issue by ergerd** [mrRobot62/GCodeGenerator_Geometricals#9]
Wenn die nächste Tiefe angefahren wird bleibt das Tool auf der bis dahin gefahrenen Höhe. Sollte m.E. auf Safety Z angehoben werden und erst am neuen Startpunkt die nächste Tiefe anfahren.

**Comment by mrRobot62** [comment]
warum sollte auf SAFETY Z gefahren werden, wenn man z.B. von -0.5 auf -0.6 gehen will?

**Comment by ergerd** [comment]
Ich denke, erst muss doch das neue Ziel angefahren werden, oder? Hätte ich so gemacht.
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 19.11.18, 21:51, Bernd Klein <notifications@github.com> schrieb:
warum sollte auf SAFETY Z gefahren werden, wenn man z.B. von -0.5 auf -0.6 gehen will?

**Comment by mrRobot62** [comment]
Stimmt, der Fehler ist auch bei surfacheRectangle #12 drin und behoben worden

**Comment by mrRobot62** [comment]
Bugfix: #9 in Version 0.12, Z-Achse wird auf StartZ gesetzt bevor eine neue Tiefe angefahren wird

**Comment by mrRobot62** [comment]
Bugfix Release V0.12.1

**Comment by ergerd** [comment]
Jetzt wird zwar das Werkzeug angehoben, um an sein neues Ziel zu fahren, aber von Start Z wird nur der erste Tiefenstep abgezogen, so das das Werkzeug z.B. auf 2.8 mm Höhe bleibt. Es hätte auf -0.4 mm fahren müssen.

**Comment by mrRobot62** [comment]
Nee, das ist eine relative Tiefeneinstellung G91 für Z - sprich Z wird immer um -0.2 verringert vom aktuellen Punkt

Das muss man mal auf der CNC testen. Wenn das klappt ist das viel einfacher als immer eine Berechnung der aktuellen Tiefe und wie tief man überhaupt darf.

**Comment by ergerd** [comment]
Als Tool diameter habe ich 12.0 angegeben, das sind wohl Millimeter. Als work piece radius 15.0 wohl auch Millimeter. Bei 90% Stepover tooldia% hätte ich angenommen, das er so 4 oder 5 Runden dreht, um die Fläche zu bearbeiten. Er dreht aber 19 Runden.

**Comment by ergerd** [comment]
Nein, in CAMotics bleibt das Werkzeug in der Luft.

**Comment by ergerd** [comment]
![grafik](https://user-images.githubusercontent.com/44188762/48802208-cd085300-ed0e-11e8-83de-004210d5e7c5.png)

**Comment by mrRobot62** [comment]
bei 90% stepover , heißt das das bei 12mm ToolDia, 90% werden vom vorherigen Fräsdurchgang nochmals gefräst => hier als 10.8mm. Einfacher gesagt: 10% ist der Vorschob => bei 15mm Radius sind dass dann 15/1.2 = 12,5 Runden + den Overshot der bei Default 110% liegt. Somit fährt der Fräser außerhalb der Kontur (um die Kante des Frässtücks sauber zu fräsen und der Fräser später AUSSERHALB der Kontur ist

Ich weiß nicht ob CAMotics den G91 richtig interpretiert. Im GCode-Viewer wird das auch nicht angezeigt. Bin mir echt nicht sicher ob das jetzt stimmt oder falsch ist :-/
